### ISSUE TITLE
[Suggestion] Give the glyph list with their corresponding meaning

### ISSUE THREAD

**Issue by brunobord** [anna328p/linjasuwi#4]
Pretty much like the [image with all the sitelen pona glyphs here](http://tokipona.net/tp/janpije/hieroglyphs.php).
I think it'd be much valuable, especially for the *nimi sin*.

**Comment by anna328p** [comment]
Probably a good idea. I'll have to work out how to create a dynamic table like that though, I'll probably use a script to generate it from namelist.txt.
