### ISSUE TITLE
sitelen "S" li nasa li kepeken ma lili

### ISSUE THREAD

**Issue by SadaleNet** [anna328p/linjasuwi#5]
lon lipu https://linjasuwi.ap5.dev/ la sitelen "S" li nasa li kepeken ma lili:

![image](https://user-images.githubusercontent.com/4593277/107728464-1ba7ca80-6d29-11eb-8b0e-99272fd4d80d.png)

mi lukin e ona kepeken ilo "Firefox" kepeken ilo "Chrome". sitelen "S" li ike sama.

**Comment by anna328p** [comment]
aaa ni li ike mi. mi pona e ona
